# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yABGvwp9tCLd_2UPFgEAo7QGjnrkD_9a
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("tanishqdublish/stock-market-predictions")

print("Path to dataset files:", path)



import pandas as pd
data=pd.read_csv(path+"/Combined_News_DJIA.csv")
data.head(100)

data.shape

from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

texts = []
scores = []

for _, row in data.iterrows():
    for i in range(1, 26):
        text = str(row[f"Top{i}"])
        texts.append(text)
        scores.append(26 - i)  #

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(texts)

model = LinearRegression()
model.fit(X, scores)

import joblib
joblib.dump(model,"/content/model.pkl")

joblib.dump(vectorizer,"/content/vectorizer.pkl")

import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_extraction.text import TfidfVectorizer
texts=[]
scores=[]
print("inited data")
for _,row in data.iterrows():
  for i in range(1,26):
    text=str(row[f"Top{i}"])
    texts.append(text)
    scores.append(26-i)
    print("added")
print("loaded data")
print("start training")
vectorizerr= TfidfVectorizer(stop_words='english')

XX = vectorizerr.fit_transform(texts)
model=RandomForestRegressor()
model.fit(XX,scores)
joblib.dump(model,"/content/forestmodelreg.pkl")
joblib.dump(vectorizerr,"/content/vectorizerr.pkl")

data=data.head(3000)
import joblib
from sklearn.ensemble import RandomForestRegressor
from sklearn.feature_extraction.text import TfidfVectorizer

texts = []
scores = []

print("inited data")

for _, row in data.iterrows():
    for i in range(1, 26):
        text = str(row[f"Top{i}"])

        # 🔥 CLEAN TEXT (important)
        text = text.replace("b'", "").replace('b"', "").strip()

        texts.append(text)
        scores.append(26 - i)

print("loaded data")
print("start training")

# ✅ TF-IDF
vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000   # limit features for speed
)

X = vectorizer.fit_transform(texts)

# ✅ RANDOM FOREST (optimized)
model = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

model.fit(X, scores)

# ✅ SAVE PROPERLY
joblib.dump(model, "/content/forestmodelreg.pkl")
joblib.dump(vectorizer, "/content/vectorizerr.pkl")

print("Model saved successfully 🚀")

data=data.head(1000)
import joblib
from xgboost import XGBClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

texts = []
labels = []

for _, row in data.iterrows():
    for i in range(1, 26):
        text = str(row[f"Top{i}"])

        if i <= 5:
            label = 2
        elif i <= 15:
            label = 1
        else:
            label = 0

        texts.append(text)
        labels.append(label)

vectorizer_xgb = TfidfVectorizer(stop_words='english', max_features=5000)
X = vectorizer_xgb.fit_transform(texts)

model_xgb = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    n_jobs=-1,
    eval_metric='mlogloss'
)

model_xgb.fit(X, labels)

joblib.dump(model_xgb, "/content/xgb_classifier.pkl")
joblib.dump(vectorizer_xgb, "/content/vectorizer_xgb.pkl")

print("XGB Classifier trained ✅")

import kagglehub

# Download latest version
path = kagglehub.dataset_download("parshantkumar2033/sentiment-intensity-for-news-articles-of-sbi")

print("Path to dataset files:", path)

import os
import shutil

# Source dataset path (read-only)
SRC_FILE = "/kaggle/input/sentiment-intensity-for-news-articles-of-sbi/dataset.csv"

# Destination path in /content/
DEST_DIR = "/content/dataset"
os.makedirs(DEST_DIR, exist_ok=True)
DEST_FILE = os.path.join(DEST_DIR, "dataset.csv")

# Copy file instead of moving
shutil.copy(SRC_FILE, DEST_FILE)

print("Dataset copied to:", DEST_FILE)

# Verify
import pandas as pd
df = pd.read_csv(DEST_FILE)
print("Dataset loaded, shape:", df.shape)

import pandas as pd
data=pd.read_csv("/content/dataset/dataset.csv")
data.head(100)

import pandas as pd
import lightgbm as lgb
from sklearn.feature_extraction.text import TfidfVectorizer
import joblib

# Load dataset
data = pd.read_csv("/content/dataset/dataset.csv")

# Drop rows where 'article' is NaN
data = data.dropna(subset=['article'])

# Vectorize
vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
X = vectorizer.fit_transform(data['article'])

# Target
Y = data['sentiment_score'].values

# Train LightGBM
model = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1, num_leaves=31)
model.fit(X, Y)

# Save
joblib.dump(model, "/content/lightmodel.pkl")
joblib.dump(vectorizer, "/content/lightvectorizer.pkl")

print("Model trained and saved successfully!")