# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yABGvwp9tCLd_2UPFgEAo7QGjnrkD_9a
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("tanishqdublish/stock-market-predictions")

print("Path to dataset files:", path)

import pandas as pd
data=pd.read_csv(path+"/Combined_News_DJIA.csv")
data.head()

from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

texts = []
scores = []

for _, row in data.iterrows():
    for i in range(1, 26):
        text = str(row[f"Top{i}"])
        texts.append(text)
        scores.append(26 - i)  #

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(texts)

model = LinearRegression()
model.fit(X, scores)

import joblib
joblib.dump(model,"/content/model.pkl")

joblib.dump(vectorizer,"/content/vectorizer.pkl")